using System;
using System.Linq;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SignLanguageApi.Data;

namespace SignLanguageApi.Data.UnitTests
{
    /// <summary>
    /// Unit tests for the <see cref="AppDbContext"/> class.
    /// </summary>
    [TestClass]
    public class AppDbContextTests
    {
        /// <summary>
        /// Tests that OnModelCreating configures a unique index on the User.Email property.
        /// Validates that the Email property has exactly one index configured and that the index is marked as unique.
        /// </summary>
        [TestMethod]
        public void OnModelCreating_UserEmailIndex_ConfiguresUniqueIndex()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act
            using AppDbContext context = new AppDbContext(options);
            IEntityType userEntity = context.Model.FindEntityType(typeof(User))!;
            IIndex? emailIndex = userEntity.GetIndexes()
                .FirstOrDefault(i => i.Properties.Any(p => p.Name == nameof(User.Email)));

            // Assert
            Assert.IsNotNull(emailIndex, "Email index should be configured");
            Assert.IsTrue(emailIndex.IsUnique, "Email index should be unique");
        }

        /// <summary>
        /// Tests that OnModelCreating configures the User.Id property with ValueGeneratedNever strategy.
        /// Validates that the Id property will not have values auto-generated by the database.
        /// </summary>
        [TestMethod]
        public void OnModelCreating_UserIdProperty_ConfiguresValueGeneratedNever()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act
            using AppDbContext context = new AppDbContext(options);
            IEntityType userEntity = context.Model.FindEntityType(typeof(User))!;
            IProperty idProperty = userEntity.FindProperty(nameof(User.Id))!;

            // Assert
            Assert.IsNotNull(idProperty, "Id property should be found");
            Assert.AreEqual(Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never, idProperty.ValueGenerated, "Id should be configured as ValueGeneratedNever");
        }

        /// <summary>
        /// Tests that OnModelCreating configures the Lesson.Difficulty property with a default SQL value of 'Beginner'.
        /// Validates that the database will use 'Beginner' as the default value when inserting new Lesson records.
        /// </summary>
        [TestMethod]
        public void OnModelCreating_LessonDifficultyProperty_ConfiguresDefaultSqlValueBeginner()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act
            using AppDbContext context = new AppDbContext(options);
            IEntityType lessonEntity = context.Model.FindEntityType(typeof(Lesson))!;
            IProperty difficultyProperty = lessonEntity.FindProperty(nameof(Lesson.Difficulty))!;
            string? defaultValueSql = difficultyProperty.GetDefaultValueSql();

            // Assert
            Assert.IsNotNull(difficultyProperty, "Difficulty property should be found");
            Assert.AreEqual("'Beginner'", defaultValueSql, "Difficulty default SQL should be 'Beginner'");
        }

        /// <summary>
        /// Tests that OnModelCreating configures the Lesson.ViewCount property with a default SQL value of 0.
        /// Validates that the database will use 0 as the default value when inserting new Lesson records.
        /// </summary>
        [TestMethod]
        public void OnModelCreating_LessonViewCountProperty_ConfiguresDefaultSqlValueZero()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act
            using AppDbContext context = new AppDbContext(options);
            IEntityType lessonEntity = context.Model.FindEntityType(typeof(Lesson))!;
            IProperty viewCountProperty = lessonEntity.FindProperty(nameof(Lesson.ViewCount))!;
            string? defaultValueSql = viewCountProperty.GetDefaultValueSql();

            // Assert
            Assert.IsNotNull(viewCountProperty, "ViewCount property should be found");
            Assert.AreEqual("0", defaultValueSql, "ViewCount default SQL should be 0");
        }

        /// <summary>
        /// Tests that OnModelCreating properly initializes the model by calling base.OnModelCreating.
        /// Validates that all configured entities (User, Lesson, LessonCategory, UserLesson, Achievement, UserAchievement, SpacedRepetitionLesson) are present in the model.
        /// </summary>
        [TestMethod]
        public void OnModelCreating_BaseMethodCalled_AllEntitiesConfigured()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act
            using AppDbContext context = new AppDbContext(options);
            IEntityType? userEntity = context.Model.FindEntityType(typeof(User));
            IEntityType? lessonEntity = context.Model.FindEntityType(typeof(Lesson));

            // Assert
            Assert.IsNotNull(userEntity, "User entity should be configured in the model");
            Assert.IsNotNull(lessonEntity, "Lesson entity should be configured in the model");
            Assert.IsNotNull(context.Model, "Model should be initialized");
        }

        /// <summary>
        /// Tests that OnModelCreating applies all User entity configurations together.
        /// Validates that both the unique Email index and ValueGeneratedNever Id configuration are applied simultaneously.
        /// </summary>
        [TestMethod]
        public void OnModelCreating_UserEntity_AppliesAllConfigurations()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act
            using AppDbContext context = new AppDbContext(options);
            IEntityType userEntity = context.Model.FindEntityType(typeof(User))!;
            IIndex? emailIndex = userEntity.GetIndexes()
                .FirstOrDefault(i => i.Properties.Any(p => p.Name == nameof(User.Email)));
            IProperty idProperty = userEntity.FindProperty(nameof(User.Id))!;

            // Assert
            Assert.IsNotNull(emailIndex, "Email index should be configured");
            Assert.IsTrue(emailIndex.IsUnique, "Email index should be unique");
            Assert.AreEqual(Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never, idProperty.ValueGenerated, "Id should be ValueGeneratedNever");
        }

        /// <summary>
        /// Tests that OnModelCreating applies all Lesson entity configurations together.
        /// Validates that both Difficulty and ViewCount default SQL values are configured simultaneously.
        /// </summary>
        [TestMethod]
        public void OnModelCreating_LessonEntity_AppliesAllConfigurations()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act
            using AppDbContext context = new AppDbContext(options);
            IEntityType lessonEntity = context.Model.FindEntityType(typeof(Lesson))!;
            IProperty difficultyProperty = lessonEntity.FindProperty(nameof(Lesson.Difficulty))!;
            IProperty viewCountProperty = lessonEntity.FindProperty(nameof(Lesson.ViewCount))!;
            string? difficultySql = difficultyProperty.GetDefaultValueSql();
            string? viewCountSql = viewCountProperty.GetDefaultValueSql();

            // Assert
            Assert.AreEqual("'Beginner'", difficultySql, "Difficulty default SQL should be 'Beginner'");
            Assert.AreEqual("0", viewCountSql, "ViewCount default SQL should be 0");
        }

        /// <summary>
        /// Tests that the constructor successfully creates an instance when provided with valid DbContextOptions.
        /// </summary>
        [TestMethod]
        public void AppDbContext_ValidOptions_CreatesInstance()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: "TestDatabase")
                .Options;

            // Act
            AppDbContext result = new AppDbContext(options);

            // Assert
            Assert.IsNotNull(result);
            Assert.IsInstanceOfType(result, typeof(AppDbContext));
        }


        /// <summary>
        /// Tests that OnModelCreating completes without throwing any exceptions.
        /// Validates that all configurations are valid and can be processed by Entity Framework Core.
        /// </summary>
        [TestMethod]
        public void OnModelCreating_ValidConfiguration_DoesNotThrowException()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act & Assert
            AppDbContext? context = null;
            try
            {
                context = new AppDbContext(options);
                IModel model = context.Model;
                Assert.IsNotNull(model, "Model should be created successfully");
            }
            finally
            {
                context?.Dispose();
            }
        }

        /// <summary>
        /// Tests that the AppDbContext constructor initializes all DbSet properties when provided with valid options.
        /// Validates that Users, Lessons, LessonCategories, UserLessons, Achievements, UserAchievements, and SpacedRepetitionLessons DbSets are all accessible after construction.
        /// </summary>
        [TestMethod]
        public void AppDbContext_ValidOptions_InitializesAllDbSets()
        {
            // Arrange
            DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;

            // Act
            using AppDbContext context = new AppDbContext(options);

            // Assert
            Assert.IsNotNull(context.Users, "Users DbSet should be initialized");
            Assert.IsNotNull(context.Lessons, "Lessons DbSet should be initialized");
            Assert.IsNotNull(context.LessonCategories, "LessonCategories DbSet should be initialized");
            Assert.IsNotNull(context.UserLessons, "UserLessons DbSet should be initialized");
            Assert.IsNotNull(context.Achievements, "Achievements DbSet should be initialized");
            Assert.IsNotNull(context.UserAchievements, "UserAchievements DbSet should be initialized");
            Assert.IsNotNull(context.SpacedRepetitionLessons, "SpacedRepetitionLessons DbSet should be initialized");
        }
    }
}