using System.Text.Json.Serialization;
using SignLanguageApp.Model;
using SignLanguageApp.Services;
using System.Collections.Generic;

namespace SignLanguageApp.Helpers
{
    [JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, PropertyNameCaseInsensitive = true, GenerationMode = JsonSourceGenerationMode.Default)]
    [JsonSerializable(typeof(LoginRequest))]
    [JsonSerializable(typeof(RegisterRequest))]
    [JsonSerializable(typeof(RefreshTokenRequest))]
    [JsonSerializable(typeof(LessonDto))]
    [JsonSerializable(typeof(LoginResponse))]
    [JsonSerializable(typeof(LoginApiResponse))]
    [JsonSerializable(typeof(User))]
    [JsonSerializable(typeof(UserStatsDto))]
    [JsonSerializable(typeof(LessonCategoryDto))]
    [JsonSerializable(typeof(LessonDetailDto))]
    [JsonSerializable(typeof(LessonStepDto))]
    [JsonSerializable(typeof(InteractiveLessonDto))]
    [JsonSerializable(typeof(LessonDetailDataDto))]
    [JsonSerializable(typeof(LessonUiLayoutDto))]
    [JsonSerializable(typeof(DailyGoalDto))]
    [JsonSerializable(typeof(LearnDataDto))]
    [JsonSerializable(typeof(DailyGoalApiDto))]
    [JsonSerializable(typeof(SpacedRepetitionLessonDto))]
    [JsonSerializable(typeof(PersonalizedRecommendationDto))]
    [JsonSerializable(typeof(UpcomingReviewsDto))]
    [JsonSerializable(typeof(UserProfileDto))]
    [JsonSerializable(typeof(WeeklyReport))]
    [JsonSerializable(typeof(DayActivity))]
    [JsonSerializable(typeof(UpdateNameRequest))]
    [JsonSerializable(typeof(UpdatePasswordRequest))]
    [JsonSerializable(typeof(UpdateAvatarRequest))]
    [JsonSerializable(typeof(UpdateDescriptionRequest))]
    [JsonSerializable(typeof(UpcomingReviewsApiDto))]
    [JsonSerializable(typeof(VideoDto))]
    [JsonSerializable(typeof(MediaDto))]
    [JsonSerializable(typeof(CoordinateDto))]
    [JsonSerializable(typeof(GesturePredictionDataDto))]
    [JsonSerializable(typeof(GesturePredictionResponseDto))]
    [JsonSerializable(typeof(ApiResponse<LoginResponse>))]
    [JsonSerializable(typeof(ApiResponse<UserStatsDto>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<LessonCategoryDto>>))]
    [JsonSerializable(typeof(ApiResponse<LessonCategoryDto>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<LessonDetailDto>>))]
    [JsonSerializable(typeof(ApiResponse<LessonDetailDto>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<LessonDto>>))]
    [JsonSerializable(typeof(ApiResponse<DailyGoalDto>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<SpacedRepetitionLessonDto>>))]
    [JsonSerializable(typeof(ApiResponse<UpcomingReviewsDto>))]
    [JsonSerializable(typeof(ApiResponse<PersonalizedRecommendationDto>))]
    [JsonSerializable(typeof(ApiResponse<InteractiveLessonDto>))]
    [JsonSerializable(typeof(ApiResponse<bool>))]
    [JsonSerializable(typeof(ApiResponse<UserProfileDto>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<VideoDto>>))]
    [JsonSerializable(typeof(ApiResponse<VideoDto>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<MediaDto>>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<SignerCreditDto>>))]
    [JsonSerializable(typeof(ApiResponse<LearnDataDto>))]
    [JsonSerializable(typeof(IEnumerable<LessonCategoryDto>))]
    [JsonSerializable(typeof(IEnumerable<LessonDetailDto>))]
    [JsonSerializable(typeof(IEnumerable<LessonDto>))]
    [JsonSerializable(typeof(IEnumerable<SpacedRepetitionLessonDto>))]
    [JsonSerializable(typeof(IEnumerable<VideoDto>))]
    [JsonSerializable(typeof(IEnumerable<MediaDto>))]
    [JsonSerializable(typeof(Dictionary<string, string>))]
    [JsonSerializable(typeof(SignPerformance))]
    [JsonSerializable(typeof(List<SignPerformance>))]
    [JsonSerializable(typeof(List<string>))]
    [JsonSerializable(typeof(DailyXpDto))]
    [JsonSerializable(typeof(CategoryProgressDto))]
    [JsonSerializable(typeof(FeedbackRequest))]
    [JsonSerializable(typeof(List<DailyXpDto>))]
    [JsonSerializable(typeof(List<CategoryProgressDto>))]
    [JsonSerializable(typeof(LeaderboardDto))]
    [JsonSerializable(typeof(LeaderboardEntryDto))]
    [JsonSerializable(typeof(IEnumerable<AchievementBadgeDto>))]
    [JsonSerializable(typeof(IEnumerable<SignerCreditDto>))]
    [JsonSerializable(typeof(List<LessonCategoryDto>))]
    [JsonSerializable(typeof(List<LessonDetailDto>))]
    [JsonSerializable(typeof(List<LessonDto>))]
    [JsonSerializable(typeof(List<SpacedRepetitionLessonDto>))]
    [JsonSerializable(typeof(List<VideoDto>))]
    [JsonSerializable(typeof(List<MediaDto>))]
    [JsonSerializable(typeof(ApiResponse<List<MediaDto>>))]
    [JsonSerializable(typeof(List<AchievementBadgeDto>))]
    [JsonSerializable(typeof(List<SignerCreditDto>))]
    [JsonSerializable(typeof(ApiResponse<List<SignerCreditDto>>))]
    [JsonSerializable(typeof(UserDto))]
    [JsonSerializable(typeof(MatchingPairDto))]
    [JsonSerializable(typeof(List<MatchingPairDto>))]
    [JsonSerializable(typeof(LessonStepType))]
    [JsonSerializable(typeof(ApiResponse<LeaderboardDto>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<LeaderboardEntryDto>>))]
    [JsonSerializable(typeof(ApiResponse<IEnumerable<AchievementBadgeDto>>))]
    [JsonSerializable(typeof(ApiResponse<GesturePredictionResponseDto>))]
    [JsonSerializable(typeof(ApiResponse<LoginApiResponse>))]
    [JsonSerializable(typeof(List<LeaderboardEntryDto>))]
    public partial class AppJsonContext : JsonSerializerContext
    {
    }
}

